const CHECKLIST_CATEGORY_CLEANING = 'cleaning'
const CHECKLIST_CATEGORY_SECURITY = 'security'
const CHECKLIST_CATEGORY_MAINTENANCE = 'maintenance'
const CHECKLIST_CATEGORY_GENERAL = 'general'

const CHECKLIST_CATEGORIES = [
    CHECKLIST_CATEGORY_CLEANING,
    CHECKLIST_CATEGORY_SECURITY,
    CHECKLIST_CATEGORY_MAINTENANCE,
    CHECKLIST_CATEGORY_GENERAL,
]

const CHECKLIST_RECURRENCE_TYPE_DAILY = 'daily'
const CHECKLIST_RECURRENCE_TYPE_WEEKLY = 'weekly'
const CHECKLIST_RECURRENCE_TYPE_MONTHLY = 'monthly'

const CHECKLIST_RECURRENCE_TYPES = [
    CHECKLIST_RECURRENCE_TYPE_DAILY,
    CHECKLIST_RECURRENCE_TYPE_WEEKLY,
    CHECKLIST_RECURRENCE_TYPE_MONTHLY,
]

module.exports = {
    CHECKLIST_CATEGORIES,
    CHECKLIST_CATEGORY_CLEANING,
    CHECKLIST_CATEGORY_SECURITY,
    CHECKLIST_CATEGORY_MAINTENANCE,
    CHECKLIST_CATEGORY_GENERAL,
    CHECKLIST_RECURRENCE_TYPES,
    CHECKLIST_RECURRENCE_TYPE_DAILY,
    CHECKLIST_RECURRENCE_TYPE_WEEKLY,
    CHECKLIST_RECURRENCE_TYPE_MONTHLY,
}
