const PUMP_ASSET_TYPE = 'pump'
const ELEVATOR_ASSET_TYPE = 'elevator'
const GENERATOR_ASSET_TYPE = 'generator'
const ELECTRICAL_PANEL_ASSET_TYPE = 'electrical_panel'
const EXTINGUISHER_ASSET_TYPE = 'extinguisher'
const GATE_ASSET_TYPE = 'gate'
const CISTERN_ASSET_TYPE = 'cistern'
const OTHER_ASSET_TYPE = 'other'

const ASSET_TYPES = [
    PUMP_ASSET_TYPE,
    ELEVATOR_ASSET_TYPE,
    GENERATOR_ASSET_TYPE,
    ELECTRICAL_PANEL_ASSET_TYPE,
    EXTINGUISHER_ASSET_TYPE,
    GATE_ASSET_TYPE,
    CISTERN_ASSET_TYPE,
    OTHER_ASSET_TYPE,
]

const ACTIVE_ASSET_STATUS = 'active'
const INACTIVE_ASSET_STATUS = 'inactive'
const IN_MAINTENANCE_ASSET_STATUS = 'in_maintenance'

const ASSET_STATUSES = [
    ACTIVE_ASSET_STATUS,
    INACTIVE_ASSET_STATUS,
    IN_MAINTENANCE_ASSET_STATUS,
]

module.exports = {
    PUMP_ASSET_TYPE,
    ELEVATOR_ASSET_TYPE,
    GENERATOR_ASSET_TYPE,
    ELECTRICAL_PANEL_ASSET_TYPE,
    EXTINGUISHER_ASSET_TYPE,
    GATE_ASSET_TYPE,
    CISTERN_ASSET_TYPE,
    OTHER_ASSET_TYPE,
    ASSET_TYPES,
    ACTIVE_ASSET_STATUS,
    INACTIVE_ASSET_STATUS,
    IN_MAINTENANCE_ASSET_STATUS,
    ASSET_STATUSES,
}
