const SUPPLIER_STATUS_ACTIVE = 'active'
const SUPPLIER_STATUS_INACTIVE = 'inactive'

const SUPPLIER_STATUS_TYPES = [
    SUPPLIER_STATUS_ACTIVE,
    SUPPLIER_STATUS_INACTIVE,
]

module.exports = {
    SUPPLIER_STATUS_ACTIVE,
    SUPPLIER_STATUS_INACTIVE,
    SUPPLIER_STATUS_TYPES,
}
